export const mockPlanets = [
  {
    name: 'planet1',
    population: '200',
    rotation_period: '345',
    residents: ['mira', 'mara'],
    films: ['film1', 'film2'],
    url: 'someurl',
  },
  {
    name: 'planet2',
    population: '200',
    rotation_period: '345',
    residents: ['mira', 'mara'],
    films: ['film1', 'film2'],
    url: 'someurl',
  },
  {
    name: 'planet3',
    population: '200',
    rotation_period: '345',
    residents: ['mira', 'mara'],
    films: ['film1', 'film2'],
    url: 'someurl',
  },
  {
    name: 'planet4',
    population: '200',
    rotation_period: '345',
    residents: ['mira', 'mara'],
    films: ['film1', 'film2'],
    url: 'someurl',
  },
  {
    name: 'planet5',
    population: '200',
    rotation_period: '345',
    residents: ['mira', 'mara'],
    films: ['film1', 'film2'],
    url: 'someurl',
  },
]
